# Generated by Django 2.2.8 on 2019-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(default='', max_length=200)),
                ('nama_barang', models.CharField(default='', max_length=100)),
                ('deskripsi', models.TextField(default='')),
                ('harga', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
